### ISSUE TITLE
Javascript client code parsing: parameter check

### ISSUE THREAD

**Issue by nephilim** [kayemkim/milonga#5]
EncodedSource.indexOf("request") < SomeNumber doesn't make sense. The result of indexOf method will be -1 when it's failed. 

The condition above is true even the string is not found.

**Comment by nephilim** [comment]
All *CheckPolicy classes check the condition using indexOf method

**Comment by kayemkim** [comment]
Got it. I'll try to correct bugs.

**Comment by kayemkim** [comment]
Issue has been fixed. Please check ArgumentCheckPolicy-implemented classes.
