### ISSUE TITLE
Retrieving Spring Bean

### ISSUE THREAD

**Issue by kayemkim** [kayemkim/milonga#9]

**Comment by nephilim** [comment]
향후 Spring의 Application Context를 불러올 수 있어야 한다.
1. curried된 표기로 handler 앞에 context를 바인딩할 인자 변수를 표기하는 것은 어떨까?
   (일단 떠올려봄)

function handler(context)(“/my-url/”, request,response) {
    // … 
}

**Comment by kayemkim** [comment]
Using Spring application context, it is possible to access Spring beans.
